logging:
  level:
    root: INFO

server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:file:~/ccwDb;MODE=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: embedded