DROP SCHEMA IF EXISTS CCW CASCADE;

CREATE SCHEMA CCW;

CREATE TABLE CCW.CASE_STAGES
(
    CASE_STAGE_ID       VARCHAR(10)  NOT NULL
    CONSTRAINT pk_case_stage_id PRIMARY KEY (case_stage_id)
);

CREATE TABLE CCW.PROVIDER_LOCATIONS
(
    PROVIDER_LOCATION_ID    VARCHAR(10)  NOT NULL,
    DESCRIPTION             VARCHAR(150) NOT NULL,
    CONSTRAINT pk_provider_location_id PRIMARY KEY (provider_location_id)
);

CREATE TABLE CCW.LEVEL_CODES
(
    LEVEL_CODE_ID       VARCHAR(10)  NOT NULL,
    DESCRIPTION         VARCHAR(150) NOT NULL,
    CONSTRAINT pk_level_code_id PRIMARY KEY (level_code_id)
);

CREATE TABLE CCW.MATTER_CODES_1
(
    MATTER_CODE_ID      VARCHAR(10)  NOT NULL
    CONSTRAINT pk_matter_code_id PRIMARY KEY (matter_code_id)
);

CREATE TABLE CCW.MATTER_CODES_COMBINATIONS
(
    MATTER_CODE_1   VARCHAR(10)    NOT NULL,
    MATTER_CODE_2   VARCHAR(500)   NOT NULL,
    CONSTRAINT fk_matter_codes_1_matter_code_1 FOREIGN KEY (MATTER_CODE_1) REFERENCES MATTER_CODES_1(MATTER_CODE_ID)
);

CREATE TABLE CCW.CASE_STAGES_COMBINATIONS
(
    MATTER_CODE_1   VARCHAR(10)    NOT NULL,
    CASE_STAGES   VARCHAR(500)   NOT NULL,
    CONSTRAINT fk_matter_codes_1_matter_code_1 FOREIGN KEY (MATTER_CODE_1) REFERENCES MATTER_CODES_1(MATTER_CODE_ID)
);

CREATE TABLE CCW.FIXED_FEES
(
    FIXED_FEE_ID       UUID         NOT NULL DEFAULT sys_guid(),
    FIXED_AMOUNT       NUMBER(8,2)  NOT NULL,
    CASE_STAGE         VARCHAR(10)  NOT NULL,
    LEVEL_CODE         VARCHAR(10)  NOT NULL,
    PROVIDER_LOCATION  VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_fixed_fee_id PRIMARY KEY (fixed_fee_id)
    CONSTRAINT fk_case_stages_case_stage FOREIGN KEY (CASE_STAGE) REFERENCES CASE_STAGES(CASE_STAGE_ID),
    CONSTRAINT fk_level_codes_level_code FOREIGN KEY (LEVEL_CODE) REFERENCES LEVEL_CODES(LEVEL_CODE_ID),
    CONSTRAINT fk_provider_locations_provider_location FOREIGN KEY (PROVIDER_LOCATION) REFERENCES PROVIDER_LOCATIONS(PROVIDER_LOCATION_ID)
);