apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laa-ccw-fees-service-service-monitor
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: laa-ccw-fees-service-service # this needs to match the label in the service under metadata:labels:app
  namespaceSelector:
    matchNames:
      - ${NAMESPACE}
  endpoints:
    - port: http # this is the port name you grabbed from your running service
      interval: 60s
      path: /actuator/prometheus # this is the endpoint exposed by springboot app